/* Generated by Claude 3.7*/
import React, { useState, useEffect } from 'react';
import { 
  Card, 
  Form, 
  Button, 
  InputGroup, 
  Badge, 
  Row, 
  Col,
  ButtonGroup
} from 'react-bootstrap';
import { 
  FaTrash, 
  FaPlus, 
  FaEdit, 
  FaCheck, 
  FaEye,
  FaTimes 
} from 'react-icons/fa';
import './QuestionEditor.css';

// Question type interface
export interface Choice {
  id?: string;
  text: string;
  isCorrect: boolean;
}

export interface Question {
  _id?: string;
  title: string;
  questionType: string;
  questionText: string;
  points: number;
  choices?: Choice[];
  correctAnswer?: boolean;
  correctAnswers?: string[];
  isEditing?: boolean;
}

interface QuestionEditorProps {
  question: Question;
  index: number;
  onUpdate: (index: number, updatedQuestion: Question) => void;
  onRemove: (index: number) => void;
  isNew?: boolean;
}

const QuestionEditor: React.FC<QuestionEditorProps> = ({ 
  question, 
  index, 
  onUpdate, 
  onRemove,
  isNew = false
}) => {
  const [editingQuestion, setEditingQuestion] = useState<Question>({...question});
  const [isEditing, setIsEditing] = useState<boolean>(isNew || question.isEditing || false);
  const [originalQuestion, setOriginalQuestion] = useState<Question>({...question});

  // Update local state when external question data changes
  useEffect(() => {
    setEditingQuestion({...question});
    setOriginalQuestion({...question});
    setIsEditing(isNew || question.isEditing || false);
  }, [question, isNew]);

  // Handle question field changes
  const handleQuestionChange = (field: string, value: any) => {
    const updatedQuestion = { ...editingQuestion, [field]: value };
    
    // If question type is changed, reset answer-related fields
    if (field === 'questionType') {
      if (value === 'MULTIPLE_CHOICE') {
        updatedQuestion.choices = [
          { id: Date.now().toString(), text: 'Option 1', isCorrect: false },
          { id: Date.now().toString() + '1', text: 'Option 2', isCorrect: false }
        ];
        delete updatedQuestion.correctAnswer;
        delete updatedQuestion.correctAnswers;
      } else if (value === 'TRUE_FALSE') {
        updatedQuestion.correctAnswer = false;
        delete updatedQuestion.choices;
        delete updatedQuestion.correctAnswers;
      } else if (value === 'FILL_BLANK') {
        updatedQuestion.correctAnswers = [''];
        delete updatedQuestion.choices;
        delete updatedQuestion.correctAnswer;
      }
    }
    
    setEditingQuestion(updatedQuestion);
  };

  // Handle choice changes (multiple choice)
  const handleChoiceChange = (choiceIndex: number, field: string, value: any) => {
    if (!editingQuestion.choices) return;
    
    const newChoices = [...editingQuestion.choices];
    
    if (field === 'isCorrect') {
      // Single choice logic: ensure only one option is selected
      newChoices.forEach((choice, i) => {
        if (i === choiceIndex) {
          choice.isCorrect = true;
        } else {
          choice.isCorrect = false;
        }
      });
    } else {
      // @ts-ignore: dynamic property assignment
      newChoices[choiceIndex][field] = value;
    }
    
    setEditingQuestion({ ...editingQuestion, choices: newChoices });
  };

  // Add new option (multiple choice)
  const addChoice = () => {
    if (!editingQuestion.choices) return;
    
    const newChoice: Choice = {
      id: Date.now().toString(),
      text: `Option ${editingQuestion.choices.length + 1}`,
      isCorrect: false
    };
    
    setEditingQuestion({
      ...editingQuestion,
      choices: [...editingQuestion.choices, newChoice]
    });
  };

  // Delete option (multiple choice)
  const removeChoice = (choiceIndex: number) => {
    if (!editingQuestion.choices) return;
    
    const newChoices = [...editingQuestion.choices];
    newChoices.splice(choiceIndex, 1);
    
    // If correct answer is deleted, automatically set the first option as correct
    const hasCorrectChoice = newChoices.some(choice => choice.isCorrect);
    if (!hasCorrectChoice && newChoices.length > 0) {
      newChoices[0].isCorrect = true;
    }
    
    setEditingQuestion({ ...editingQuestion, choices: newChoices });
  };

  // Handle fill-in-the-blank answer changes
  const handleCorrectAnswerChange = (answerIndex: number, value: string) => {
    if (!editingQuestion.correctAnswers) return;
    
    const newAnswers = [...editingQuestion.correctAnswers];
    newAnswers[answerIndex] = value;
    
    setEditingQuestion({ ...editingQuestion, correctAnswers: newAnswers });
  };

  // Add new fill-in-the-blank answer
  const addCorrectAnswer = () => {
    if (!editingQuestion.correctAnswers) return;
    
    setEditingQuestion({
      ...editingQuestion,
      correctAnswers: [...editingQuestion.correctAnswers, '']
    });
  };

  // Delete fill-in-the-blank answer
  const removeCorrectAnswer = (answerIndex: number) => {
    if (!editingQuestion.correctAnswers) return;
    
    const newAnswers = [...editingQuestion.correctAnswers];
    newAnswers.splice(answerIndex, 1);
    
    setEditingQuestion({ ...editingQuestion, correctAnswers: newAnswers });
  };

  // Save question
  const saveQuestion = () => {
    // Ensure at least one correct option (multiple choice)
    if (editingQuestion.questionType === 'MULTIPLE_CHOICE' && 
        editingQuestion.choices && 
        !editingQuestion.choices.some(choice => choice.isCorrect)) {
      if (editingQuestion.choices.length > 0) {
        editingQuestion.choices[0].isCorrect = true;
      }
    }
    
    // Update question, close edit mode
    onUpdate(index, { ...editingQuestion, isEditing: false });
    setIsEditing(false);
  };

  // Cancel editing
  const cancelEdit = () => {
    // Restore original question data
    setEditingQuestion({...originalQuestion});
    
    // If it's a new question and canceled, delete it
    if (isNew) {
      onRemove(index);
    } else {
      // Close edit mode
      onUpdate(index, { ...originalQuestion, isEditing: false });
      setIsEditing(false);
    }
  };

  // Start editing
  const startEditing = () => {
    setOriginalQuestion({...editingQuestion});
    setIsEditing(true);
    onUpdate(index, { ...editingQuestion, isEditing: true });
  };

  // Render multiple choice editor
  const renderMultipleChoiceEditor = () => {
    return (
      <div className="mt-3">
        <Form.Label className="fw-bold">Options:</Form.Label>
        <div className="choices-container">
          {editingQuestion.choices && editingQuestion.choices.map((choice, choiceIndex) => (
            <InputGroup key={choice.id || choiceIndex} className="mb-2">
              <InputGroup.Radio 
                checked={choice.isCorrect}
                onChange={() => handleChoiceChange(choiceIndex, 'isCorrect', true)}
                name={`choice-correct-${index}`}
                aria-label="Select as correct answer"
              />
              <Form.Control
                value={choice.text}
                onChange={(e) => handleChoiceChange(choiceIndex, 'text', e.target.value)}
                placeholder={`Option ${choiceIndex + 1}`}
              />
              <Button 
                variant="outline-danger"
                onClick={() => removeChoice(choiceIndex)}
                disabled={editingQuestion.choices && editingQuestion.choices.length <= 2}
              >
                <FaTrash />
              </Button>
            </InputGroup>
          ))}
          <Button
            variant="outline-secondary"
            size="sm"
            className="mt-2"
            onClick={addChoice}
          >
            <FaPlus className="me-1" /> Add Option
          </Button>
        </div>
      </div>
    );
  };

  // Render true/false editor
  const renderTrueFalseEditor = () => {
    return (
      <div className="mt-3">
        <Form.Label className="fw-bold">Correct Answer:</Form.Label>
        <div>
          <Form.Check
            type="radio"
            id={`true-${index}`}
            name={`true-false-${index}`}
            label="True"
            inline
            checked={editingQuestion.correctAnswer === true}
            onChange={() => handleQuestionChange('correctAnswer', true)}
            className="me-3"
          />
          <Form.Check
            type="radio"
            id={`false-${index}`}
            name={`true-false-${index}`}
            label="False"
            inline
            checked={editingQuestion.correctAnswer === false}
            onChange={() => handleQuestionChange('correctAnswer', false)}
          />
        </div>
      </div>
    );
  };

  // Render fill-in-the-blank editor
  const renderFillBlankEditor = () => {
    return (
      <div className="mt-3">
        <Form.Label className="fw-bold">Acceptable Answers:</Form.Label>
        <p className="text-muted small">Student's response must exactly match one of the acceptable answers to receive credit.</p>
        <div className="answers-container">
          {editingQuestion.correctAnswers && editingQuestion.correctAnswers.map((answer, answerIndex) => (
            <InputGroup key={answerIndex} className="mb-2">
              <InputGroup.Text>{answerIndex + 1}</InputGroup.Text>
              <Form.Control
                value={answer}
                onChange={(e) => handleCorrectAnswerChange(answerIndex, e.target.value)}
                placeholder="Enter acceptable answer"
              />
              <Button 
                variant="outline-danger"
                onClick={() => removeCorrectAnswer(answerIndex)}
                disabled={editingQuestion.correctAnswers?.length === 1}
              >
                <FaTrash />
              </Button>
            </InputGroup>
          ))}
          <Button
            variant="outline-secondary"
            size="sm"
            className="mt-2"
            onClick={addCorrectAnswer}
          >
            <FaPlus className="me-1" /> Add Answer Option
          </Button>
        </div>
      </div>
    );
  };

  // Render the appropriate editor based on question type
  const renderQuestionTypeEditor = () => {
    switch (editingQuestion.questionType) {
      case 'MULTIPLE_CHOICE':
        return renderMultipleChoiceEditor();
      case 'TRUE_FALSE':
        return renderTrueFalseEditor();
      case 'FILL_BLANK':
        return renderFillBlankEditor();
      default:
        return null;
    }
  };

  // Render question preview (non-edit mode)
  const renderQuestionPreview = () => {
    return (
      <Card className="question-preview">
        <Card.Header className="d-flex justify-content-between align-items-center">
          <div className="d-flex align-items-center">
            <span className="question-number">{index + 1}.</span>
            <span className="question-title ms-2">{question.title}</span>
          </div>
          <div>
            <Badge bg="primary" className="me-2">{question.points} points</Badge>
            <Badge bg="secondary" className="me-2">
              {question.questionType === 'MULTIPLE_CHOICE' ? 'Multiple Choice' : 
               question.questionType === 'TRUE_FALSE' ? 'True/False' : 'Fill in the Blank'}
            </Badge>
            <ButtonGroup size="sm">
              <Button variant="outline-primary" onClick={startEditing}>
                <FaEdit />
              </Button>
              <Button variant="outline-danger" onClick={() => onRemove(index)}>
                <FaTrash />
              </Button>
            </ButtonGroup>
          </div>
        </Card.Header>
        <Card.Body>
          <div className="question-text mb-3">{question.questionText}</div>
          
          {question.questionType === 'MULTIPLE_CHOICE' && question.choices && (
            <div className="choices-preview">
              {question.choices.map((choice, i) => (
                <div key={i} className={`choice-item ${choice.isCorrect ? 'correct-choice' : ''}`}>
                  <span className="choice-marker">{choice.isCorrect ? <FaCheck className="text-success" /> : <FaTimes className="text-muted" />}</span>
                  <span className="choice-text">{choice.text}</span>
                </div>
              ))}
            </div>
          )}
          
          {question.questionType === 'TRUE_FALSE' && (
            <div className="true-false-preview">
              <div className={`choice-item ${question.correctAnswer ? 'correct-choice' : ''}`}>
                <span className="choice-marker">{question.correctAnswer ? <FaCheck className="text-success" /> : <FaTimes className="text-muted" />}</span>
                <span className="choice-text">True</span>
              </div>
              <div className={`choice-item ${!question.correctAnswer ? 'correct-choice' : ''}`}>
                <span className="choice-marker">{!question.correctAnswer ? <FaCheck className="text-success" /> : <FaTimes className="text-muted" />}</span>
                <span className="choice-text">False</span>
              </div>
            </div>
          )}
          
          {question.questionType === 'FILL_BLANK' && question.correctAnswers && (
            <div className="fill-blank-preview">
              <p>Correct Answers:</p>
              <ul className="answers-list">
                {question.correctAnswers.map((answer, i) => (
                  <li key={i}>{answer}</li>
                ))}
              </ul>
            </div>
          )}
        </Card.Body>
      </Card>
    );
  };

  return isEditing ? (
    <Card className="question-editor mb-3">
      <Card.Header className="d-flex justify-content-between align-items-center">
        <div className="d-flex align-items-center">
          <span className="question-number">{index + 1}.</span>
          <Form.Control
            type="text"
            value={editingQuestion.title}
            onChange={(e) => handleQuestionChange('title', e.target.value)}
            placeholder="Question Title"
            className="question-title-input ms-2"
          />
        </div>
        <div className="d-flex align-items-center">
          <Form.Group className="points-input me-2">
            <InputGroup>
              <Form.Control
                type="number"
                min="0"
                value={editingQuestion.points}
                onChange={(e) => handleQuestionChange('points', parseInt(e.target.value) || 0)}
                aria-label="Question points"
              />
              <InputGroup.Text>points</InputGroup.Text>
            </InputGroup>
          </Form.Group>
          <Form.Select
            value={editingQuestion.questionType}
            onChange={(e) => handleQuestionChange('questionType', e.target.value)}
            className="question-type-select me-2"
            style={{ width: 'auto' }}
          >
            <option value="MULTIPLE_CHOICE">Multiple Choice</option>
            <option value="TRUE_FALSE">True/False</option>
            <option value="FILL_BLANK">Fill in the Blank</option>
          </Form.Select>
        </div>
      </Card.Header>
      <Card.Body>
        <Form.Group className="mb-3">
          <Form.Label className="fw-bold">Question Text:</Form.Label>
          <div className="editor-toolbar">
            <div className="btn-group">
              <button type="button" className="btn btn-sm btn-outline-secondary">Edit</button>
              <button type="button" className="btn btn-sm btn-outline-secondary">View</button>
              <button type="button" className="btn btn-sm btn-outline-secondary">Insert</button>
              <button type="button" className="btn btn-sm btn-outline-secondary">Format</button>
              <button type="button" className="btn btn-sm btn-outline-secondary">Tools</button>
              <button type="button" className="btn btn-sm btn-outline-secondary">Table</button>
            </div>
            <div className="btn-group ms-2">
              <button type="button" className="btn btn-sm btn-outline-secondary">B</button>
              <button type="button" className="btn btn-sm btn-outline-secondary"><i>I</i></button>
              <button type="button" className="btn btn-sm btn-outline-secondary"><u>U</u></button>
            </div>
          </div>
          <Form.Control
            as="textarea"
            rows={3}
            value={editingQuestion.questionText}
            onChange={(e) => handleQuestionChange('questionText', e.target.value)}
            placeholder="Enter question content..."
          />
        </Form.Group>

        {renderQuestionTypeEditor()}

        <div className="d-flex justify-content-end mt-4">
          <Button 
            variant="outline-secondary" 
            className="me-2"
            onClick={cancelEdit}
          >
            Cancel
          </Button>
          <Button 
            variant="danger" 
            onClick={saveQuestion}
          >
            <FaCheck className="me-1" /> Confirm Question
          </Button>
        </div>
      </Card.Body>
    </Card>
  ) : (
    renderQuestionPreview()
  );
};

export default QuestionEditor; 