/* Generated by Claude 3.7*/
import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  getQuizzesForCourse, 
  deleteQuiz,
  publishQuiz,
  unpublishQuiz,
  createAttempt,
  getAttemptsForQuiz
} from './api';
import { 
  Button, 
  Container, 
  Row, 
  Col, 
  Badge, 
  Alert, 
  Card, 
  Dropdown, 
  ListGroup, 
  Spinner,
  Modal
} from 'react-bootstrap';
import { 
  FaPlus, 
  FaEllipsisV, 
  FaBan, 
  FaCheck, 
  FaCalendarAlt,
  FaQuestionCircle
} from 'react-icons/fa';
import './QuizzesList.css'; // Import style file
import { useSelector } from 'react-redux';

// Quiz interface definition
interface Quiz {
  _id: string;
  title: string;
  description: string;
  totalPoints: number;
  published: boolean;
  dueDate?: Date;
  availableDate?: Date;
  untilDate?: Date;
  questions: any[];
  quizType: string;
}

// Student attempt interface
interface Attempt {
  _id: string;
  score: number;
  completed: boolean;
}

// Format date display helper
const formatDate = (dateString?: Date) => {
  if (!dateString) return 'No date specified'; 
  const date = new Date(dateString);
  // Format to MM/DD/YYYY HH:MM AM/PM
  return `${date.toLocaleDateString()} ${date.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}`;
};

function QuizzesList() {
  const { cid } = useParams<{ cid: string }>();
  const navigate = useNavigate();
  const [quizzes, setQuizzes] = useState<Quiz[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<'name' | 'dueDate' | 'availableDate'>('name');
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [quizToDelete, setQuizToDelete] = useState<string | null>(null);
  const [userRole, setUserRole] = useState<'student' | 'instructor' | null>(null); // Initialize as null
  const [studentAttempts, setStudentAttempts] = useState<Record<string, Attempt>>({});
  const { currentUser } = useSelector((state: any) => state.accountReducer);

  // Update userRole based on currentUser from Redux
  useEffect(() => {
    if (currentUser && currentUser.role) {
      console.log("Current user role:", currentUser.role);
      if (currentUser.role === 'FACULTY' || currentUser.role === 'INSTRUCTOR') {
        setUserRole('instructor');
      } else if (currentUser.role === 'STUDENT') {
        setUserRole('student');
      } else {
        setUserRole(null); // Handle other roles if necessary, or default
      }
    } else {
        setUserRole(null); // No user or role
    }
  }, [currentUser]);

  // Get quiz list
  const fetchQuizzes = async () => {
    if (!cid) {
      setError("Unable to get course ID");
      return;
    }
    
    try {
      setLoading(true);
      setError(null);
      
      const data = await getQuizzesForCourse(cid);
      
      if (Array.isArray(data)) {
        setQuizzes(data);
      } else if (data && typeof data === 'object') {
        const quizData = Array.isArray(data.quizzes) ? data.quizzes : 
                        (Array.isArray(data.quiz) ? data.quiz : 
                        (data.quizzes || data.quiz ? [data.quizzes || data.quiz] : []));
        setQuizzes(quizData);
      } else {
        setQuizzes([]);
      }
    } catch (err: any) {
      console.error('Error getting quiz list:', err);
      setError(err.message || 'Failed to get quiz list');
      setQuizzes([]);
    } finally {
      setLoading(false);
    }
  };

  // Fetch quizzes on initial load or when course ID changes
  useEffect(() => {
    if (cid) { // Ensure cid is available
         fetchQuizzes();
    } else {
        setError("Course ID is missing.");
        setQuizzes([]); // Clear quizzes if no course ID
    }
  }, [cid]);

  // 2. Add useEffect to fetch student attempts
  useEffect(() => {
    // Only run if user is student and quizzes list is populated
    if (userRole === 'student' && quizzes.length > 0 && cid) {
      const fetchAllAttempts = async () => {
        console.log("Fetching attempts for student:", currentUser?._id);
        // Can reuse loading state or add a dedicated one
        // setLoading(true);
        try {
          const attemptPromises = quizzes.map(quiz =>
            getAttemptsForQuiz(quiz._id) // Call API for each quiz
              .then(attemptsArray => {
                // Assuming API returns an array of attempts
                if (Array.isArray(attemptsArray) && attemptsArray.length > 0) {
                  // Sort by startTime descending to find the last attempt
                  const sortedAttempts = [...attemptsArray].sort((a, b) => {
                      if (a.startTime && b.startTime) {
                          return new Date(b.startTime).getTime() - new Date(a.startTime).getTime();
                      }
                      // Fallback to _id if startTime is missing (assuming chronological)
                       return b._id.localeCompare(a._id);
                  });
                  return { quizId: quiz._id, lastAttempt: sortedAttempts[0] }; // Return object with quizId and last attempt
                }
                return { quizId: quiz._id, lastAttempt: null }; // No attempts found
              })
              .catch(error => {
                console.error(`Failed to get attempts for quiz ${quiz._id}:`, error);
                return { quizId: quiz._id, lastAttempt: null }; // Handle individual fetch error
              })
          );

          // Wait for all requests to complete
          const results = await Promise.all(attemptPromises);

          // Convert results to a { quizId: attempt } map
          const newAttemptsMap: Record<string, Attempt> = {};
          results.forEach(result => {
            if (result.lastAttempt) {
              newAttemptsMap[result.quizId] = result.lastAttempt;
            }
          });

          console.log("Fetched student attempts map:", newAttemptsMap);
          setStudentAttempts(newAttemptsMap); // Update state

        } catch (error) {
          console.error("Error fetching student attempts:", error);
          // Optionally set an error state
        } finally {
          // setLoading(false); // If loading state was used
        }
      };

      fetchAllAttempts();
    }
    // Clear attempts if user is not a student or no quizzes
    else if (userRole !== 'student' || quizzes.length === 0) {
         console.log("Resetting student attempts.");
         setStudentAttempts({});
     }
     // Dependencies: re-run when quizzes, userRole, cid, or currentUser change
  }, [quizzes, userRole, cid, currentUser]); // Added currentUser to ensure student ID is available

  // Create new quiz
  const handleCreateQuiz = () => {
    navigate(`/Kambaz/Courses/${cid}/Quizzes/new`);
  };

  // Navigate to quiz details page
  const handleViewQuiz = (quizId: string) => {
    if (cid) {
      navigate(`/Kambaz/Courses/${cid}/Quizzes/${quizId}`);
    } else {
      navigate(`/Kambaz/Quizzes/${quizId}`);
    }
  };

  // Navigate to quiz edit page
  const handleEditQuiz = (quizId: string) => {
    navigate(`/Kambaz/Quizzes/${quizId}/edit`);
  };

  // Confirm quiz deletion
  const confirmDeleteQuiz = (quizId: string) => {
    setQuizToDelete(quizId);
    setShowDeleteModal(true);
  };

  // Delete quiz
  const handleDeleteQuiz = async () => {
    if (!quizToDelete) return;
    
    try {
      setLoading(true);
      await deleteQuiz(quizToDelete);
      // Update list after successful deletion
      setQuizzes(quizzes.filter(quiz => quiz._id !== quizToDelete));
      setShowDeleteModal(false);
      setQuizToDelete(null);
    } catch (err: any) {
      console.error('Failed to delete quiz:', err);
      setError(err.message || 'Failed to delete quiz');
    } finally {
      setLoading(false);
    }
  };

  // Publish/unpublish quiz
  const togglePublishQuiz = async (quizId: string, isPublished: boolean) => {
    try {
      setLoading(true);
      
      if (isPublished) {
        await unpublishQuiz(quizId);
      } else {
        await publishQuiz(quizId);
      }
      
      // Update quiz status in the list
      setQuizzes(quizzes.map(quiz => {
        if (quiz._id === quizId) {
          return { ...quiz, published: !isPublished };
        }
        return quiz;
      }));
    } catch (err: any) {
      console.error(`Failed to ${isPublished ? 'unpublish' : 'publish'} quiz:`, err);
      setError(err.message || `Failed to ${isPublished ? 'unpublish' : 'publish'} quiz`);
    } finally {
      setLoading(false);
    }
  };

  // Copy quiz to other course (optional)
  const handleCopyQuiz = (quizId: string) => {
    // Could open a modal here to select target course
    console.log('Copy quiz:', quizId);
  };

  // Sort quizzes
  const handleSort = (sortType: 'name' | 'dueDate' | 'availableDate') => {
    setSortBy(sortType);
    
    const sortedQuizzes = [...quizzes].sort((a, b) => {
      if (sortType === 'name') {
        return a.title.localeCompare(b.title);
      } else if (sortType === 'dueDate') {
        const dateA = a.dueDate ? new Date(a.dueDate).getTime() : Infinity;
        const dateB = b.dueDate ? new Date(b.dueDate).getTime() : Infinity;
        return dateA - dateB;
      } else { // availableDate
        const dateA = a.availableDate ? new Date(a.availableDate).getTime() : Infinity;
        const dateB = b.availableDate ? new Date(b.availableDate).getTime() : Infinity;
        return dateA - dateB;
      }
    });
    
    setQuizzes(sortedQuizzes);
  };

  // Get quiz availability status
  const getAvailabilityStatus = (quiz: Quiz) => {
    const now = new Date();
    const availableDate = quiz.availableDate ? new Date(quiz.availableDate) : null;
    const untilDate = quiz.untilDate ? new Date(quiz.untilDate) : null;

    // Condition 1: Before Available Date
    if (availableDate && now < availableDate) {
      return {
        status: `Not available until ${formatDate(availableDate)}`,
        label: `Available on: ${formatDate(availableDate)}`,
        color: 'secondary'
      };
    }

    // Condition 2: After Until Date
    if (untilDate && now > untilDate) {
      return {
        status: 'Closed',
        label: 'Ended',
        color: 'dark'
      };
    }

    // Condition 3: Between Available and Until (or no Until)
    return {
      status: 'Available',
      label: 'Available',
      color: 'success'
    };
  };

  // Empty state component
  const EmptyState = () => (
    <Card className="empty-state-card">
      <Card.Body>
        <FaQuestionCircle className="empty-state-icon" />
        <Card.Title>No Quizzes Yet</Card.Title>
        <Card.Text>
          {userRole === 'instructor' 
            ? "Click the \"+ Quiz\" button to create a new quiz" 
            : "There are no quizzes available right now"}
        </Card.Text>
        {userRole === 'instructor' && (
          <Button 
            variant="primary" 
            onClick={handleCreateQuiz}
            className="d-flex align-items-center mx-auto add-quiz-btn"
          >
            <FaPlus className="me-2" /> Add Quiz
          </Button>
        )}
      </Card.Body>
    </Card>
  );

  // Function to check if a user can modify a quiz
  const canModifyQuiz = () => {
    return userRole === 'instructor'; // Only instructors/faculty can modify quizzes
  }

  // Function to check if a quiz is available for students to take
  const isQuizAvailable = (quiz: Quiz) => {
    if (userRole === 'instructor') return true; // Instructors see all quizzes
    
    // For students, check if quiz is published and within available dates
    if (!quiz.published) return false;
    
    const now = new Date();
    const availableDate = quiz.availableDate ? new Date(quiz.availableDate) : null;
    const untilDate = quiz.untilDate ? new Date(quiz.untilDate) : null;
    
    // Not available yet
    if (availableDate && now < availableDate) return false;
    
    // Already closed
    if (untilDate && now > untilDate) return false;
    
    return true;
  };

  if (loading && quizzes.length === 0) {
    return (
      <Container className="text-center my-5">
        <Spinner animation="border" role="status">
          <span className="visually-hidden">Loading...</span>
        </Spinner>
      </Container>
    );
  }

  return (
    <Container className="quiz-list-container">
      <div className="quizzes-header">
        <h2>Course Quizzes</h2>
        <div className="d-flex gap-2">
          <Dropdown>
            <Dropdown.Toggle variant="outline-secondary" id="sort-dropdown" className="sort-dropdown">
              Sort by: {
                sortBy === 'name' ? 'Name' : 
                sortBy === 'dueDate' ? 'Due Date' : 'Available Date'
              }
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item onClick={() => handleSort('name')}>Name</Dropdown.Item>
              <Dropdown.Item onClick={() => handleSort('dueDate')}>Due Date</Dropdown.Item>
              <Dropdown.Item onClick={() => handleSort('availableDate')}>Available Date</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
          {canModifyQuiz() && (
            <Button 
              variant="danger" 
              onClick={handleCreateQuiz}
              className="d-flex align-items-center add-quiz-btn"
            >
              <FaPlus className="me-2" /> Quiz
            </Button>
          )}
        </div>
      </div>
      
      {error && <Alert variant="danger">{error}</Alert>}
      
      {quizzes.length === 0 ? (
        userRole === 'instructor' ? <EmptyState /> : (
          <Card className="empty-state-card">
            <Card.Body>
              <FaQuestionCircle className="empty-state-icon" />
              <Card.Title>No Quizzes</Card.Title>
              <Card.Text>There are no quizzes available right now</Card.Text>
            </Card.Body>
          </Card>
        )
      ) : (
        <ListGroup>
          {quizzes.map(quiz => {
            const availabilityInfo = getAvailabilityStatus(quiz);
            // Skip quizzes that aren't available for students
            if (userRole === 'student' && !isQuizAvailable(quiz)) return null;
            
            return (
              <ListGroup.Item key={quiz._id} className={`p-0 mb-2 border quiz-item ${quiz.published ? 'published' : 'unpublished'}`}>
                <Row className="m-0 p-0 align-items-center">
                  {/* Published status icon - only visible to instructors */}
                  <Col xs={userRole === 'instructor' ? 1 : 0} className="text-center py-3">
                    {userRole === 'instructor' && (
                      quiz.published ? (
                        <div 
                          className="quiz-status-icon published" 
                          title="Published, click to unpublish"
                          onClick={() => togglePublishQuiz(quiz._id, true)}
                        >
                          <FaCheck />
                        </div>
                      ) : (
                        <div 
                          className="quiz-status-icon unpublished" 
                          title="Unpublished, click to publish"
                          onClick={() => togglePublishQuiz(quiz._id, false)}
                        >
                          <FaBan />
                        </div>
                      )
                    )}
                  </Col>
                  
                  {/* Quiz info (title/type etc) */}
                  <Col xs={userRole === 'instructor' ? 8 : 12} className="py-3">
                    <div 
                      className="quiz-title" 
                      onClick={() => handleViewQuiz(quiz._id)}
                    >
                      {quiz.title}
                    </div>
                    <div className="quiz-details">
                      <Badge bg={availabilityInfo.color as any}>{availabilityInfo.status}</Badge>
                      <span className="quiz-detail-item">
                        <FaCalendarAlt />
                        Due date: {formatDate(quiz.dueDate)}
                      </span>
                      <span className="quiz-detail-item">{quiz.totalPoints} points</span>
                      <span className="quiz-detail-item">{quiz.questions?.length || 0} questions</span>
                      {userRole === 'student' && studentAttempts[quiz._id] && (
                        <span className="quiz-detail-item fw-bold">
                          Score: {studentAttempts[quiz._id].score} / {quiz.totalPoints}
                        </span>
                      )}
                    </div>
                  </Col>
                  
                  {/* Right action buttons - only visible to instructors */}
                  {userRole === 'instructor' && (
                    <Col xs={3} className="d-flex justify-content-end py-3 pe-3 quiz-actions">
                      <Dropdown>
                        <Dropdown.Toggle variant="light" id={`dropdown-${quiz._id}`}>
                          <FaEllipsisV />
                        </Dropdown.Toggle>
                        <Dropdown.Menu>
                          <Dropdown.Item onClick={() => handleEditQuiz(quiz._id)}>Edit</Dropdown.Item>
                          <Dropdown.Item onClick={() => confirmDeleteQuiz(quiz._id)}>Delete</Dropdown.Item>
                          <Dropdown.Item onClick={() => togglePublishQuiz(quiz._id, quiz.published)}>
                            {quiz.published ? 'Unpublish' : 'Publish'}
                          </Dropdown.Item>
                          <Dropdown.Item onClick={() => handleCopyQuiz(quiz._id)}>Copy to another course</Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </Col>
                  )}

                  {/* Student-specific actions */}
                  {userRole === 'student' && (
                    <Col xs={3} className="d-flex justify-content-end py-3 pe-3 quiz-actions">
                      {/* Show Take Quiz button if attempt is allowed */}
                      {!studentAttempts[quiz._id] && (
                        <Button
                          variant="success"
                          onClick={async () => {
                            try {
                              console.log(`Attempting to start quiz: ${quiz._id}`);
                              const response = await createAttempt(quiz._id);
                              
                              if (response && response.data && response.data._id) {
                                const newAttemptId = response.data._id;
                                console.log(`Attempt created: ${newAttemptId}, navigating to attempt page.`);
                                navigate(`/Kambaz/Courses/${cid}/Quizzes/${quiz._id}/attempt`, {
                                  state: {
                                    attemptId: newAttemptId,
                                    courseId: cid
                                  }
                                });
                              } else {
                                console.error("Failed to create quiz attempt or missing attempt ID in response:", response);
                                alert("Failed to start quiz. Attempt data is missing.");
                              }
                            } catch (error: any) {
                              console.error("Error starting quiz attempt:", error);
                              alert(`Failed to start quiz: ${error.response?.data?.message || error.message || 'Unknown error'}`);
                            }
                          }}
                        >
                          Take Quiz
                        </Button>
                      )}
                      
                      {/* If student has completed the quiz, show their score and a View Results button */}
                      {studentAttempts[quiz._id] && studentAttempts[quiz._id].completed && (
                        <Button 
                          variant="info"
                          onClick={() => navigate(`/Kambaz/Courses/${cid}/Quizzes/${quiz._id}/results`)}
                        >
                          View Results
                        </Button>
                      )}
                    </Col>
                  )}
                </Row>
              </ListGroup.Item>
            );
          })}
        </ListGroup>
      )}
      
      {/* Delete confirmation dialog */}
      <Modal show={showDeleteModal} onHide={() => setShowDeleteModal(false)} className="delete-confirm-modal">
        <Modal.Header closeButton>
          <Modal.Title>Confirm Deletion</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          Are you sure you want to delete this quiz? This action cannot be undone.
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowDeleteModal(false)}>
            Cancel
          </Button>
          <Button variant="danger" onClick={handleDeleteQuiz}>
            Delete
          </Button>
        </Modal.Footer>
      </Modal>
    </Container>
  );
}

export default QuizzesList;