/* Generated by Claude 3.7*/
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  Form, 
  Button, 
  Container, 
  Card, 
  Row, 
  Col, 
  Alert, 
  Nav, 
  Tab, 
  InputGroup,
  Badge,
  FormCheck 
} from 'react-bootstrap';
import { createQuiz, getQuizById, updateQuiz, publishQuiz } from './api';
import { 
  FaSave, 
  FaArrowLeft, 
  FaPlus, 
  FaTrash, 
  FaCalendarAlt, 
  FaLock, 
  FaClock,
  FaEye,
  FaCamera,
  FaRandom,
  FaLayerGroup,
  FaKey,
  FaCheck,
  FaExclamationCircle
} from 'react-icons/fa';
import './QuizEditor.css';
import QuestionEditor, { Question } from './QuestionEditor';

// Create a simplified version of the editor, can be expanded in the future

interface Quiz {
  _id: string;
  title: string;
  description?: string;
  quizType: string;
  timeLimit: number;
  shuffleAnswers: boolean;
  multipleAttempts: boolean;
  attemptsAllowed: number;
  showCorrectAnswers: boolean;
  oneQuestionAtTime: boolean;
  webcamRequired: boolean;
  lockQuestionsAfterAnswering: boolean;
  accessCode: string;
  assignmentGroup: string;
  dueDate?: Date;
  availableDate?: Date;
  untilDate?: Date;
  questions: Question[];
  course?: string;
}

function QuizEditor() {
  const { cid, quizId } = useParams<{ cid?: string; quizId?: string }>();
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState('details');
  const [courserId, setCourserId] = useState<string | undefined>(cid);
  
  // Quiz basic information
  const [title, setTitle] = useState('Untitled Quiz');
  const [description, setDescription] = useState('');
  const [quizType, setQuizType] = useState('GRADED_QUIZ');
  const [timeLimit, setTimeLimit] = useState(20);
  const [shuffleAnswers, setShuffleAnswers] = useState(true);
  const [multipleAttempts, setMultipleAttempts] = useState(false);
  const [attemptsAllowed, setAttemptsAllowed] = useState(1);
  const [showCorrectAnswers, setShowCorrectAnswers] = useState(false);
  const [oneQuestionAtTime, setOneQuestionAtTime] = useState(true);
  const [webcamRequired, setWebcamRequired] = useState(false);
  const [lockQuestionsAfterAnswering, setLockQuestionsAfterAnswering] = useState(false);
  const [accessCode, setAccessCode] = useState('');
  const [assignmentGroup, setAssignmentGroup] = useState('QUIZZES');
  const [dueDate, setDueDate] = useState<string>('');
  const [availableDate, setAvailableDate] = useState<string>('');
  const [untilDate, setUntilDate] = useState<string>('');
  
  // Question list
  const [questions, setQuestions] = useState<Question[]>([]);
  // Track which questions have been confirmed
  const [confirmedQuestions, setConfirmedQuestions] = useState<boolean[]>([]);
  // Track if the current question form is dirty (has unsaved changes)
  const [hasUnconfirmedQuestion, setHasUnconfirmedQuestion] = useState(false);

  // If in edit mode, load existing quiz data
  useEffect(() => {
    if (quizId) {
      const fetchQuiz = async () => {
        try {
          setLoading(true);
          const response = await getQuizById(quizId);
          const quiz = response.data;
          
          // Record the course ID if it exists in the quiz data
          console.log("Loaded quiz data:", quiz);
          if (quiz.course && !cid) {
            console.log("Quiz belongs to course:", quiz.course);
            // Save course ID to state variable
            setCourserId(quiz.course);
          }
          
          // Fill the form
          setTitle(quiz.title || 'Untitled Quiz');
          setDescription(quiz.description || '');
          setQuizType(quiz.quizType || 'GRADED_QUIZ');
          setTimeLimit(quiz.timeLimit || 20);
          setShuffleAnswers(quiz.shuffleAnswers !== undefined ? quiz.shuffleAnswers : true);
          setMultipleAttempts(quiz.multipleAttempts || false);
          setAttemptsAllowed(quiz.attemptsAllowed || 1);
          setShowCorrectAnswers(quiz.showCorrectAnswers || false);
          setQuestions(quiz.questions || []);
          // For existing quizzes, mark all questions as confirmed
          setConfirmedQuestions(Array(quiz.questions?.length || 0).fill(true));
          setOneQuestionAtTime(quiz.oneQuestionAtTime !== undefined ? quiz.oneQuestionAtTime : true);
          setWebcamRequired(quiz.webcamRequired || false);
          setLockQuestionsAfterAnswering(quiz.lockQuestionsAfterAnswering || false);
          setAccessCode(quiz.accessCode || '');
          setAssignmentGroup(quiz.assignmentGroup || 'QUIZZES');
          
          // Handle date format
          if (quiz.dueDate) {
            setDueDate(formatDateForInput(new Date(quiz.dueDate)));
          }
          if (quiz.availableDate) {
            setAvailableDate(formatDateForInput(new Date(quiz.availableDate)));
          }
          if (quiz.untilDate) {
            setUntilDate(formatDateForInput(new Date(quiz.untilDate)));
          }
        } catch (err: any) {
          setError(err.message || 'Failed to get quiz');
        } finally {
          setLoading(false);
        }
      };
      
      fetchQuiz();
    }
  }, [quizId]);

  // Date formatting function
  const formatDateForInput = (date: Date): string => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    
    return `${year}-${month}-${day}T${hours}:${minutes}`;
  };

  // Add new question
  const addQuestion = () => {
    const newQuestion: Question = {
      title: `Question ${questions.length + 1}`,
      questionType: 'MULTIPLE_CHOICE',
      questionText: '',
      points: 1,
      choices: [
        { text: 'Option 1', isCorrect: false },
        { text: 'Option 2', isCorrect: false }
      ],
      isEditing: false  // Default to preview mode
    };
    
    setQuestions([...questions, newQuestion]);
    // Mark the new question as not saved initially
    setConfirmedQuestions([...confirmedQuestions, false]);
  };

  // Delete question
  const removeQuestion = (index: number) => {
    const newQuestions = [...questions];
    newQuestions.splice(index, 1);
    setQuestions(newQuestions);
    
    // Also remove this question's confirmation status
    const newConfirmedQuestions = [...confirmedQuestions];
    newConfirmedQuestions.splice(index, 1);
    setConfirmedQuestions(newConfirmedQuestions);
  };

  // Confirm the question
  const confirmQuestion = (index: number) => {
    const newConfirmedQuestions = [...confirmedQuestions];
    newConfirmedQuestions[index] = true;
    setConfirmedQuestions(newConfirmedQuestions);
  };

  // Update question
  const updateQuestion = (index: number, updatedQuestion: Question) => {
    const newQuestions = [...questions];
    newQuestions[index] = updatedQuestion;
    setQuestions(newQuestions);
    
    const newConfirmedQuestions = [...confirmedQuestions];
    
    // If the question is not in editing mode, it means the user has confirmed it
    // We should mark it as confirmed
    if (!updatedQuestion.isEditing) {
      newConfirmedQuestions[index] = true;
      setConfirmedQuestions(newConfirmedQuestions);
      console.log(`Question ${index} has been confirmed`);
    } else {
      // Mark as unconfirmed if the question is being edited
      newConfirmedQuestions[index] = false;
      setConfirmedQuestions(newConfirmedQuestions);
      console.log(`Question ${index} is now being edited`);
    }
  };

  // Calculate total points
  const calculateTotalPoints = (): number => {
    return questions.reduce((total, question) => total + question.points, 0);
  };

  // Save quiz
  const handleSave = async (e: React.FormEvent, shouldPublish: boolean = false) => {
    e.preventDefault();


    
    // Check if any questions are unconfirmed
    if (confirmedQuestions.includes(false)) {
      setError("All questions must be saved before saving the quiz. Please save each question by clicking the 'Save Question' button.");
      setActiveTab('questions');
      return; // Prevent saving
    }
    
    // Calculate total points
    const totalPoints = calculateTotalPoints();
    
    // Collect quiz data
    const quizData = {
      title,
      description,
      quizType,
      timeLimit,
      shuffleAnswers,
      multipleAttempts,
      attemptsAllowed,
      showCorrectAnswers,
      oneQuestionAtTime,
      webcamRequired,
      lockQuestionsAfterAnswering,
      accessCode,
      assignmentGroup,
      dueDate: dueDate ? new Date(dueDate) : undefined,
      availableDate: availableDate ? new Date(availableDate) : undefined,
      untilDate: untilDate ? new Date(untilDate) : undefined,
      questions: questions.map(q => {
        // Remove isEditing property to ensure it's not saved to database
        const { isEditing, ...questionData } = q;
        return questionData;
      }),
      course: cid
    };
    
    try {
      setLoading(true);
      setError(null);
      
      let savedQuiz: Quiz | undefined;
      
      if (quizId) {
        // Update existing quiz
        const response = await updateQuiz(quizId, quizData);
        savedQuiz = response;
        setSuccess('Quiz has been successfully updated');
      } else if (cid) {
        // Create new quiz
        const response = await createQuiz(cid, quizData);
        savedQuiz = response;
        setSuccess('Quiz has been successfully created');
      }
      
      if (shouldPublish && savedQuiz) {
        try {
          // Publish quiz
          await publishQuiz(savedQuiz._id);
          setSuccess(prevSuccess => `${prevSuccess} and published`);
          
          // Get course ID from the saved quiz data
          setTimeout(() => {
            // Use the course ID from the saved quiz (if exists)
            if (savedQuiz.course) {
              navigate(`/Kambaz/Courses/${savedQuiz.course}/Quizzes`);
            } else if (courserId) {
              navigate(`/Kambaz/Courses/${courserId}/Quizzes`);
            } else if (cid) {
              navigate(`/Kambaz/Courses/${cid}/Quizzes`);
            } else {
              // If no course ID is available, navigate to quiz details page
              navigate(`/Kambaz/Quizzes/${savedQuiz._id}`);
            }
          }, 1000);
        } catch (pubErr) {
          console.error("Failed to publish quiz", pubErr);
          setError('Quiz has been saved, but publishing failed');
        }
      } else if (!shouldPublish) {
        // If no need to publish, navigate to quiz details page
        setTimeout(() => {
          if (quizId) {
            navigate(`/Kambaz/Quizzes/${quizId}`);
          } else if (savedQuiz) {
            navigate(`/Kambaz/Quizzes/${savedQuiz._id}`);
          }
        }, 1000);
      }
    } catch (err: any) {
      console.error("Error saving quiz:", err);
      if (err.response) {
        setError(`Failed to save quiz (${err.response.status}): ${err.response.data?.message || err.message}`);
      } else if (err.request) {
        setError(`Request received no response: ${err.message} - Please confirm if the server is running`);
      } else {
        setError(`Error: ${err.message}`);
      }
    } finally {
      setLoading(false);
    }
  };

  // Cancel editing
  const handleCancel = () => {
    if (courserId) {
      navigate(`/Kambaz/Courses/${courserId}/Quizzes`);
    } else if (cid) {
      navigate(`/Kambaz/Courses/${cid}/Quizzes`);
    } else if (quizId) {
      navigate(`/Kambaz/Quizzes/${quizId}`);
    } else {
      navigate('/Kambaz/Dashboard');
    }
  };

  if (loading && !title) return (
    <Container className="text-center my-5">
      <div className="spinner-border" role="status">
        <span className="visually-hidden">Loading...</span>
      </div>
    </Container>
  );

  return (
    <Container className="my-4 quiz-editor-container">
      <Tab.Container activeKey={activeTab} onSelect={(key) => setActiveTab(key || 'details')}>
        {/* Title and main action buttons */}
        <div className="d-flex justify-content-between align-items-center mb-4">
          <h2 className="page-title">{quizId ? 'Edit Quiz' : 'Create New Quiz'}</h2>
          <div className="action-buttons">
            <Button 
              variant="outline-secondary"
              className="me-2"
              onClick={handleCancel}
              disabled={loading}
            >
              Cancel
            </Button>
            <Button 
              variant="outline-primary"
              className="me-2"
              onClick={(e) => handleSave(e)}
              disabled={loading}
            >
              <FaSave className="me-1" /> Save
            </Button>
            <Button 
              variant="success"
              onClick={(e) => handleSave(e, true)}
              disabled={loading}
            >
              <FaSave className="me-1" /> Save and Publish
            </Button>
          </div>
        </div>

        {/* Error and success alerts */}
        {error && <Alert variant="danger">{error}</Alert>}
        {success && <Alert variant="success">{success}</Alert>}

        {/* Quiz title input */}
        <Card className="mb-3">
          <Card.Body>
            <Form.Group className="mb-0">
              <Form.Control 
                type="text" 
                value={title} 
                onChange={(e) => setTitle(e.target.value)}
                required
                className="quiz-title-input"
                placeholder="Quiz Title"
              />
            </Form.Group>
          </Card.Body>
        </Card>

        {/* Tab navigation */}
        <Nav variant="tabs" className="mb-3">
          <Nav.Item>
            <Nav.Link eventKey="details">Details</Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link eventKey="questions">
              Questions 
              <Badge bg="secondary" className="ms-2">{questions.length}</Badge>
            </Nav.Link>
          </Nav.Item>
        </Nav>

        {/* Tab content */}
        <Tab.Content>
          {/* Details tab */}
          <Tab.Pane eventKey="details">
            <Form>
              <Card className="mb-4">
                <Card.Body>
                  {/* Quiz description - WYSIWYG editor */}
                  <Form.Group className="mb-4">
                    <Form.Label>Quiz Description</Form.Label>
                    <div className="editor-toolbar">
                      <div className="btn-group">
                        <button type="button" className="btn btn-sm btn-outline-secondary">Edit</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary">Insert</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary">Format</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary">Tools</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary">Table</button>
                      </div>
                      <div className="btn-group ms-2">
                        <button type="button" className="btn btn-sm btn-outline-secondary">B</button>
                        <button type="button" className="btn btn-sm btn-outline-secondary"><i>I</i></button>
                        <button type="button" className="btn btn-sm btn-outline-secondary"><u>U</u></button>
                      </div>
                    </div>
                    <Form.Control 
                      as="textarea" 
                      rows={4} 
                      value={description} 
                      onChange={(e) => setDescription(e.target.value)}
                      placeholder="Enter quiz description..."
                    />
                  </Form.Group>

                  <Row className="mb-3">
                    <Col md={6}>
                      {/* Quiz type */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaLayerGroup className="me-2" />
                          Quiz Type
                        </Form.Label>
                        <Form.Select 
                          value={quizType} 
                          onChange={(e) => setQuizType(e.target.value)}
                        >
                          <option value="GRADED_QUIZ">Graded Quiz</option>
                          <option value="PRACTICE_QUIZ">Practice Quiz</option>
                          <option value="GRADED_SURVEY">Graded Survey</option>
                          <option value="UNGRADED_SURVEY">Ungraded Survey</option>
                        </Form.Select>
                      </Form.Group>
                    </Col>
                    <Col md={6}>
                      {/* Total points */}
                      <Form.Group className="mb-3">
                        <Form.Label>Total Points</Form.Label>
                        <Form.Control 
                          type="text" 
                          value={calculateTotalPoints()}
                          disabled
                        />
                        <Form.Text className="text-muted">
                          Total points is the sum of all question points
                        </Form.Text>
                      </Form.Group>
                    </Col>
                  </Row>

                  <Row className="mb-3">
                    <Col md={6}>
                      {/* Assignment group */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaLayerGroup className="me-2" />
                          Assignment Group
                        </Form.Label>
                        <Form.Select 
                          value={assignmentGroup} 
                          onChange={(e) => setAssignmentGroup(e.target.value)}
                        >
                          <option value="QUIZZES">Quizzes</option>
                          <option value="EXAMS">Exams</option>
                          <option value="ASSIGNMENTS">Assignments</option>
                          <option value="PROJECT">Projects</option>
                        </Form.Select>
                      </Form.Group>
                    </Col>
                    <Col md={6}>
                      {/* Access code */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaKey className="me-2" />
                          Access Code
                        </Form.Label>
                        <Form.Control 
                          type="text" 
                          value={accessCode} 
                          onChange={(e) => setAccessCode(e.target.value)}
                          placeholder="Not set"
                        />
                        <Form.Text className="text-muted">
                          Optional: Access code that students need to enter
                        </Form.Text>
                      </Form.Group>
                    </Col>
                  </Row>

                  <hr className="my-4" />

                  <Row className="mb-3">
                    <Col md={6}>
                      {/* Time limit */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaClock className="me-2" />
                          Time Limit
                        </Form.Label>
                        <InputGroup>
                          <Form.Control 
                            type="number" 
                            min="1"
                            value={timeLimit} 
                            onChange={(e) => setTimeLimit(parseInt(e.target.value) || 20)}
                          />
                          <InputGroup.Text>minutes</InputGroup.Text>
                        </InputGroup>
                      </Form.Group>
                    </Col>
                    <Col md={6}>
                      {/* Shuffle answers */}
                      <Form.Group className="mb-3 pt-2">
                        <Form.Check 
                          type="switch"
                          id="shuffle-answers"
                          label={<><FaRandom className="me-2" />Shuffle Answers</>}
                          checked={shuffleAnswers}
                          onChange={(e) => setShuffleAnswers(e.target.checked)}
                        />
                      </Form.Group>

                      {/* One question at a time */}
                      <Form.Group className="mb-3">
                        <Form.Check 
                          type="switch"
                          id="one-question-at-time"
                          label="One Question at a Time"
                          checked={oneQuestionAtTime}
                          onChange={(e) => setOneQuestionAtTime(e.target.checked)}
                        />
                      </Form.Group>
                    </Col>
                  </Row>

                  <Row className="mb-3">
                    <Col md={6}>
                      {/* Allow multiple attempts */}
                      <Form.Group className="mb-3">
                        <Form.Check 
                          type="switch"
                          id="multiple-attempts"
                          label="Allow Multiple Attempts"
                          checked={multipleAttempts}
                          onChange={(e) => setMultipleAttempts(e.target.checked)}
                        />
                        
                        {multipleAttempts && (
                          <InputGroup className="mt-2">
                            <Form.Control 
                              type="number" 
                              min="1"
                              value={attemptsAllowed} 
                              onChange={(e) => setAttemptsAllowed(parseInt(e.target.value) || 1)}
                            />
                            <InputGroup.Text>attempts</InputGroup.Text>
                          </InputGroup>
                        )}
                      </Form.Group>
                    </Col>
                    <Col md={6}>
                      {/* Show correct answers */}
                      <Form.Group className="mb-3">
                        <Form.Check 
                          type="switch"
                          id="show-correct-answers"
                          label={<><FaEye className="me-2" />Show Correct Answers</>}
                          checked={showCorrectAnswers}
                          onChange={(e) => setShowCorrectAnswers(e.target.checked)}
                        />
                      </Form.Group>
                    </Col>
                  </Row>

                  <Row className="mb-3">
                    <Col md={6}>
                      {/* Require webcam */}
                      <Form.Group className="mb-3">
                        <Form.Check 
                          type="switch"
                          id="webcam-required"
                          label={<><FaCamera className="me-2" />Require Webcam</>}
                          checked={webcamRequired}
                          onChange={(e) => setWebcamRequired(e.target.checked)}
                        />
                      </Form.Group>
                    </Col>
                    <Col md={6}>
                      {/* Lock questions after answering */}
                      <Form.Group className="mb-3">
                        <Form.Check 
                          type="switch"
                          id="lock-questions"
                          label={<><FaLock className="me-2" />Lock Questions After Answering</>}
                          checked={lockQuestionsAfterAnswering}
                          onChange={(e) => setLockQuestionsAfterAnswering(e.target.checked)}
                        />
                      </Form.Group>
                    </Col>
                  </Row>

                  <hr className="my-4" />

                  <h5 className="mb-3">Time Settings</h5>
                  <Row>
                    <Col md={4}>
                      {/* Available from date */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaCalendarAlt className="me-2" />
                          Available From
                        </Form.Label>
                        <Form.Control 
                          type="datetime-local" 
                          value={availableDate} 
                          onChange={(e) => setAvailableDate(e.target.value)}
                        />
                      </Form.Group>
                    </Col>
                    <Col md={4}>
                      {/* Due date */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaCalendarAlt className="me-2" />
                          Due Date
                        </Form.Label>
                        <Form.Control 
                          type="datetime-local" 
                          value={dueDate} 
                          onChange={(e) => setDueDate(e.target.value)}
                        />
                      </Form.Group>
                    </Col>
                    <Col md={4}>
                      {/* Until date */}
                      <Form.Group className="mb-3">
                        <Form.Label>
                          <FaCalendarAlt className="me-2" />
                          Available Until
                        </Form.Label>
                        <Form.Control 
                          type="datetime-local" 
                          value={untilDate} 
                          onChange={(e) => setUntilDate(e.target.value)}
                        />
                      </Form.Group>
                    </Col>
                  </Row>
                </Card.Body>
              </Card>
            </Form>
          </Tab.Pane>

          {/* Questions tab */}
          <Tab.Pane eventKey="questions">
            {questions.length === 0 && (
              <Alert variant="info" className="mb-3">
                <div className="d-flex align-items-center">
                  <FaExclamationCircle className="me-2" />
                  <div>
                    <strong>No questions yet.</strong> You need to add at least one question before saving the quiz.
                  </div>
                </div>
              </Alert>
            )}
            
            {confirmedQuestions.includes(false) && (
              <Alert variant="warning" className="mb-3">
                <div className="d-flex align-items-center">
                  <FaExclamationCircle className="me-2" />
                  <div>
                    <strong>Unsaved questions detected.</strong> Please save all questions before saving the quiz.
                  </div>
                </div>
              </Alert>
            )}
            
            <Card className="mb-4">
              <Card.Body>
                <div className="d-flex justify-content-between align-items-center mb-4">
                  <div>
                    <h4 className="mb-0">Quiz Questions</h4>
                    <div className="text-muted">Total: {calculateTotalPoints()} points</div>
                  </div>
                  <Button 
                    variant="primary" 
                    onClick={addQuestion}
                    className="d-flex align-items-center"
                  >
                    <FaPlus className="me-1" /> Add Question
                  </Button>
                </div>
  
                {questions.length === 0 ? (
                  <div className="text-center py-5">
                    <div className="mb-3">
                      <FaPlus style={{ fontSize: '3rem', opacity: 0.3 }} />
                    </div>
                    <h5>No Questions Yet</h5>
                    <p className="text-muted">Click the "Add Question" button to create your first question</p>
                  </div>
                ) : (
                  <div className="questions-list">
                    {questions.map((question, index) => (
                      <div key={question._id || index} className="mb-4">
                        <div className={`question-card ${!confirmedQuestions[index] ? 'unconfirmed-question' : 'confirmed-question'}`}>
                          {!confirmedQuestions[index] && (
                            <div className="unconfirmed-badge">
                              <Badge bg="warning" className="mb-2">Needs Saving</Badge>
                            </div>
                          )}
                          {confirmedQuestions[index] && (
                            <div className="confirmed-badge">
                              <Badge bg="success" className="mb-2">
                                <FaCheck className="me-1" /> Saved
                              </Badge>
                            </div>
                          )}
                          <QuestionEditor
                            question={question}
                            index={index}
                            onUpdate={updateQuestion}
                            onRemove={removeQuestion}
                            isNew={!question._id}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </Card.Body>
            </Card>
          </Tab.Pane>
        </Tab.Content>
      </Tab.Container>

      {/* Bottom action buttons */}
      <div className="d-flex justify-content-between mt-4">
        <Button 
          variant="outline-secondary"
          onClick={handleCancel}
          disabled={loading}
        >
          Cancel
        </Button>
        <div>
          <Button 
            variant="outline-primary"
            className="me-2"
            onClick={(e) => handleSave(e)}
            disabled={loading}
          >
            <FaSave className="me-1" /> Save
          </Button>
          <Button 
            variant="success"
            onClick={(e) => handleSave(e, true)}
            disabled={loading}
          >
            <FaSave className="me-1" /> Save and Publish
          </Button>
        </div>
      </div>
    </Container>
  );
}

export default QuizEditor;