import { Form, Button, Container } from 'react-bootstrap';
import { Link, useParams } from 'react-router-dom';
import { assignments } from '../../Database';


{/*Generated by AI*/}
export default function AssignmentEditor() {
    const { cid, aid } = useParams();
    const assignment = assignments.find((a) => a._id === aid);
    console.log(assignment);
    return (
        <Container id="wd-assignments-editor">
            <Form>
                <Form.Group className="mb-3">
                    <Form.Label htmlFor="wd-name">Assignment Name</Form.Label>
                    <Form.Control 
                        id="wd-name" 
                        defaultValue={assignment?.title || ""} 
                    />
                </Form.Group>

                <Form.Group className="mb-3">
                    <Form.Control
                        as="textarea"
                        id="wd-description"
                        rows={3}
                        defaultValue={assignment?.description || ""}
                    />
                </Form.Group>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Points
                    </Form.Label>
                    <Form.Control 
                        type="number" 
                        defaultValue={assignment?.points || 100} 
                    />
                </div>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Assignment Group
                    </Form.Label>
                    <Form.Select style={{ textTransform: 'uppercase' }}>
                        <option>Assignments</option>
                        <option>Quizzes</option>
                        <option>Exams</option>
                        <option>Projects</option>
                    </Form.Select>
                </div>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Display Grade as
                    </Form.Label>
                    <Form.Select>
                        <option>Percentage</option>
                        <option>Letter</option>
                    </Form.Select>
                </div>

                <div className="d-flex align-items-start mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Submission Type
                    </Form.Label>
                    <div className="border rounded p-3 flex-grow-1">
                        <Form.Select className="mb-3">
                            <option>Online</option>
                            <option>On Paper</option>
                        </Form.Select>

                        <div>
                            <Form.Label className="fw-bold">Online Entry Options</Form.Label>
                            <div>
                                <Form.Check type="checkbox" label="Text Entry" />
                                <Form.Check type="checkbox" label="Website URL" defaultChecked />
                                <Form.Check type="checkbox" label="Media Recordings" />
                                <Form.Check type="checkbox" label="Student Annotation" />
                                <Form.Check type="checkbox" label="File Uploads" />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="mb-3">
                    <Form.Label>Assign to</Form.Label>
                    <div className="d-flex align-items-center gap-2">
                        <Form.Control defaultValue="Everyone" readOnly />
                        <Button variant="light">×</Button>
                    </div>
                </div>

                <div className="mb-3">
                    <Form.Label>Due</Form.Label>
                    <Form.Control 
                        type="datetime-local" 
                        defaultValue={assignment?.due || "2024-05-13T23:59"} 
                    />
                </div>

                <div className="d-flex gap-3 mb-3">
                    <div className="flex-grow-1">
                        <Form.Label>Available from</Form.Label>
                        <Form.Control 
                            type="datetime-local" 
                            defaultValue={assignment?.availableFrom || "2024-05-06T12:00"} 
                        />
                    </div>
                    <div className="flex-grow-1">
                        <Form.Label>Until</Form.Label>
                        <Form.Control 
                            type="datetime-local"
                            defaultValue={assignment?.availableUntil} 
                        />
                    </div>
                </div>

                <hr />
                <div className="d-flex gap-2">
                    <Link 
                        to={`/Kambaz/Courses/${cid}/Assignments`}
                        className="btn btn-secondary" 
                        id="wd-assignment-cancel"
                    >
                        Cancel
                    </Link>
                    <Link 
                        to={`/Kambaz/Courses/${cid}/Assignments`}
                        className="btn btn-danger" 
                        id="wd-assignment-save"
                    >
                        Save
                    </Link>
                </div>
            </Form>
        </Container>
    );
}
  