import { Form, Button, Container } from 'react-bootstrap';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { addAssignment, updateAssignment } from './reducer';



{/*Generated by AI*/}
export default function AssignmentEditor() {
    const { cid, aid } = useParams();
    const dispatch = useDispatch();
    const navigate = useNavigate();
    




    const assignment = useSelector((state: any) => 
        state.assignmentsReducer.assignments.find((a: any) => a._id === aid)
    );

    const handleAddAssignment = (formData: any) => {
            if (aid && aid !== "new") {

                dispatch(updateAssignment({ ...formData, _id: aid }));
            } else {

                const action = addAssignment(formData);
         
                dispatch(action);
            }
            navigate(`/Kambaz/Courses/${cid}/Assignments`);
            

        
    };

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        
        const form = e.currentTarget;
        const formData = {
            course: cid,
            title: (form.querySelector('#wd-name') as HTMLInputElement).value,
            description: (form.querySelector('#wd-description') as HTMLTextAreaElement).value,
            points: parseInt((form.querySelector('#wd-points') as HTMLInputElement).value),
            due: (form.querySelector('#wd-due') as HTMLInputElement).value,
            availableFrom: (form.querySelector('#wd-available-from') as HTMLInputElement).value,
            availableUntil: (form.querySelector('#wd-available-until') as HTMLInputElement).value,
        };

        handleAddAssignment(formData);
    };



    return (
        <Container id="wd-assignments-editor">
            <Form onSubmit={handleSubmit}>
                <Form.Group className="mb-3">
                    <Form.Label htmlFor="wd-name">Assignment Name</Form.Label>
                    <Form.Control 
                        id="wd-name" 
                        defaultValue={assignment?.title || ""} 
                    />
                </Form.Group>

                <Form.Group className="mb-3">
                    <Form.Control
                        as="textarea"
                        id="wd-description"
                        rows={3}
                        defaultValue={assignment?.description || ""}
                    />
                </Form.Group>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Points
                    </Form.Label>
                    <Form.Control 
                        id="wd-points"
                        type="number" 
                        defaultValue={assignment?.points || 100} 
                    />
                </div>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Assignment Group
                    </Form.Label>
                    <Form.Select style={{ textTransform: 'uppercase' }}>
                        <option>Assignments</option>
                        <option>Quizzes</option>
                        <option>Exams</option>
                        <option>Projects</option>
                    </Form.Select>
                </div>

                <div className="d-flex align-items-center mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Display Grade as
                    </Form.Label>
                    <Form.Select>
                        <option>Percentage</option>
                        <option>Letter</option>
                    </Form.Select>
                </div>

                <div className="d-flex align-items-start mb-3">
                    <Form.Label className="me-3 mb-0" style={{ width: '150px' }}>
                        Submission Type
                    </Form.Label>
                    <div className="border rounded p-3 flex-grow-1">
                        <Form.Select className="mb-3">
                            <option>Online</option>
                            <option>On Paper</option>
                        </Form.Select>

                        <div>
                            <Form.Label className="fw-bold">Online Entry Options</Form.Label>
                            <div>
                                <Form.Check type="checkbox" label="Text Entry" />
                                <Form.Check type="checkbox" label="Website URL" defaultChecked />
                                <Form.Check type="checkbox" label="Media Recordings" />
                                <Form.Check type="checkbox" label="Student Annotation" />
                                <Form.Check type="checkbox" label="File Uploads" />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="mb-3">
                    <Form.Label>Assign to</Form.Label>
                    <div className="d-flex align-items-center gap-2">
                        <Form.Control defaultValue="Everyone" readOnly />
                        <Button variant="light">×</Button>
                    </div>
                </div>

                <div className="mb-3">
                    <Form.Label>Due</Form.Label>
                    <Form.Control 
                        id="wd-due"
                        type="datetime-local" 
                        defaultValue={assignment?.due || "2024-05-13T23:59"} 
                    />
                </div>

                <div className="d-flex gap-3 mb-3">
                    <div className="flex-grow-1">
                        <Form.Label>Available from</Form.Label>
                        <Form.Control 
                            id="wd-available-from"
                            type="datetime-local" 
                            defaultValue={assignment?.availableFrom || "2024-05-06T12:00"} 
                        />
                    </div>
                    <div className="flex-grow-1">
                        <Form.Label>Until</Form.Label>
                        <Form.Control 
                            id="wd-available-until"
                            type="datetime-local"
                            defaultValue={assignment?.availableUntil} 
                        />
                    </div>
                </div>

                <hr />
                <div className="d-flex gap-2">
                    <Link 
                        to={`/Kambaz/Courses/${cid}/Assignments`}
                        className="btn btn-secondary" 
                    >
                        Cancel
                    </Link>
                    <Button 
                        type="submit"
                        variant="danger"
                        onClick={() => {
                        }}
                    >
                        Save
                    </Button>
                </div>
            </Form>
        </Container>
    );
}
  