import { useState } from "react";
import { ListGroup, Modal } from "react-bootstrap";
import { BsGripVertical, BsSearch, BsPlusLg, BsThreeDotsVertical, BsFileText, BsCheckCircleFill, BsTrash } from "react-icons/bs";
import { useParams, Link, useNavigate } from "react-router-dom";
import { useSelector, useDispatch } from "react-redux";
import { deleteAssignment } from "./reducer";


{/*Generated by AI */}
export default function Assignments() {
    const { cid } = useParams();
    const navigate = useNavigate();
    const dispatch = useDispatch();
    

    const [showDeleteDialog, setShowDeleteDialog] = useState(false);
    const [assignmentToDelete, setAssignmentToDelete] = useState<any>(null);

    const assignments = useSelector((state: any) => {
        return state.assignmentsReducer.assignments;
    });
    
    const courseAssignments = assignments.filter(
        (assignment: any) => {
            return assignment.course === cid;
        }
    );
    
    const handleAddAssignment = () => {
        navigate(`/Kambaz/Courses/${cid}/Assignments/new`);
    };


    const handleDeleteClick = (assignment: any) => {
        setAssignmentToDelete(assignment);
        setShowDeleteDialog(true);
    };

    const handleDeleteConfirm = () => {
        if (assignmentToDelete) {
            dispatch(deleteAssignment(assignmentToDelete._id));
        }
        setShowDeleteDialog(false);
        setAssignmentToDelete(null);
    };

    const handleDeleteCancel = () => {
        setShowDeleteDialog(false);
        setAssignmentToDelete(null);
    };

    return (
      <div id="wd-assignments">
        <div className="d-flex justify-content-between align-items-center mb-4 ms-4">
          <div className="position-relative flex-grow-1 me-3">
            <BsSearch className="position-absolute" style={{ left: "10px", top: "50%", transform: "translateY(-50%)" }} />
            <input 
              placeholder="Search..." 
              className="form-control ps-5"
              style={{ backgroundColor: '#f5f5f5' }}
            />
          </div>
          <button className="btn btn-light me-2">
            <BsPlusLg className="me-2" />Group
          </button>
          <button className="btn btn-danger" onClick={handleAddAssignment}>
            <BsPlusLg className="me-2" />Assignment
          </button>
        </div>

        <ListGroup className="rounded-0 ms-4" id="wd-assignments-list">
          <ListGroup.Item className="p-3 mb-4 bg-light">
            <div className="d-flex justify-content-between align-items-center">
              <div className="d-flex align-items-center">
                <BsGripVertical className="me-2 fs-5" />
                <h5 className="mb-0">ASSIGNMENTS</h5>
              </div>
              <div>
                <span className="me-2">40% of Total</span>
                <button className="btn btn-light btn-sm">
                  <BsPlusLg />
                </button>
                <button className="btn btn-light btn-sm ms-2">
                  <BsThreeDotsVertical />
                </button>
              </div>
            </div>
          </ListGroup.Item>

          {courseAssignments.map((assignment: any) => (
            <ListGroup.Item 
              key={assignment._id}
              className="p-3 mb-3"
              style={{ borderLeft: '4px solid #198754' }}
            >
              <div className="d-flex justify-content-between align-items-center">
                <Link 
                  to={`/Kambaz/Courses/${cid}/Assignments/${assignment._id}`}
                  className="text-decoration-none text-dark flex-grow-1"
                >
                  <div className="d-flex align-items-center mb-2">
                    <BsGripVertical className="me-2" />
                    <BsFileText className="me-2" />
                    <h6 className="mb-0">{assignment.title}</h6>
                  </div>
                  <div className="text-muted small">
                    <span className="text-danger">Multiple Modules</span>
                    <span className="mx-2">|</span>
                    <span>{assignment.points} pts</span>
                  </div>
                </Link>
                <div className="d-flex align-items-center">
                  <BsCheckCircleFill className="text-success me-2" />
                  <button 
                    className="btn btn-light btn-sm me-2"
                    onClick={() => handleDeleteClick(assignment)}
                  >
                    <BsTrash className="text-danger" />
                  </button>
                  <button className="btn btn-light btn-sm">
                    <BsThreeDotsVertical />
                  </button>
                </div>
              </div>
            </ListGroup.Item>
          ))}
        </ListGroup>

        {/* 刪除確認對話框 */}
        <Modal show={showDeleteDialog} onHide={handleDeleteCancel}>
          <Modal.Header closeButton>
            <Modal.Title>Delete Assignment</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            Are you sure you want to delete "{assignmentToDelete?.title}"?
          </Modal.Body>
          <Modal.Footer>
            <button className="btn btn-secondary" onClick={handleDeleteCancel}>
              Cancel
            </button>
            <button className="btn btn-danger" onClick={handleDeleteConfirm}>
              Delete
            </button>
          </Modal.Footer>
        </Modal>
      </div>
    );
}
  