import { ListGroup } from "react-bootstrap";
import { BsGripVertical, BsSearch, BsPlusLg, BsThreeDotsVertical, BsFileText, BsCheckCircleFill } from "react-icons/bs";


{/*Generated by AI */}
export default function Assignments() {
    return (
      <div id="wd-assignments">
        <div className="d-flex justify-content-between align-items-center mb-4 ms-4">
          <div className="position-relative flex-grow-1 me-3">
            <BsSearch className="position-absolute" style={{ left: "10px", top: "50%", transform: "translateY(-50%)" }} />
            <input 
              placeholder="Search..." 
              className="form-control ps-5"
              style={{ backgroundColor: '#f5f5f5' }}
            />
          </div>
          <button className="btn btn-light me-2">
            <BsPlusLg className="me-2" />Group
          </button>
          <button className="btn btn-danger">
            <BsPlusLg className="me-2" />Assignment
          </button>
        </div>

        <ListGroup className="rounded-0 ms-4" id="wd-assignments-list">
          <ListGroup.Item className="p-3 mb-4 bg-light">
            <div className="d-flex justify-content-between align-items-center">
              <div className="d-flex align-items-center">
                <BsGripVertical className="me-2 fs-5" />
                <h5 className="mb-0">ASSIGNMENTS</h5>
              </div>
              <div>
                <span className="me-2">40% of Total</span>
                <button className="btn btn-light btn-sm">
                  <BsPlusLg />
                </button>
                <button className="btn btn-light btn-sm ms-2">
                  <BsThreeDotsVertical />
                </button>
              </div>
            </div>
          </ListGroup.Item>

          {[
            { id: 121, title: 'A1', subtitle: 'ENV + HTML', date: 'May 13', available: 'May 6' },
            { id: 122, title: 'A2', subtitle: 'CSS + BOOTSTRAP', date: 'May 20', available: 'May 13' },
            { id: 123, title: 'A3', subtitle: 'JAVASCRIPT + REACT', date: 'May 27', available: 'May 20' }
          ].map((assignment) => (
            <ListGroup.Item 
              key={assignment.id}
              className="p-3 mb-3"
              style={{ borderLeft: '4px solid #198754' }}
              as="a"
              href={`#/Kambaz/Courses/1234/Assignments/${assignment.id}`}
            >
              <div className="d-flex justify-content-between align-items-center">
                <div>
                  <div className="d-flex align-items-center mb-2">
                    <BsGripVertical className="me-2" />
                    <BsFileText className="me-2" />
                    <h6 className="mb-0">{assignment.title}</h6>
                  </div>
                  <div className="text-muted small">
                    <span className="text-danger">Multiple Modules</span>
                    <span className="mx-2">|</span>
                    <span><strong>Not available until</strong> {assignment.available} at 12:00am</span> <span className="mx-2">|</span>
                    <div className="mt-1">
                      <span>Due {assignment.date} at 11:59pm</span>
                      <span className="mx-2">|</span>
                      <span>100 pts</span>
                    </div>
                  </div>
                </div>
                <div>
                  <BsCheckCircleFill className="text-success me-2" />
                  <button className="btn btn-light btn-sm">
                    <BsThreeDotsVertical />
                  </button>
                </div>
              </div>
            </ListGroup.Item>
          ))}
        </ListGroup>
      </div>
    );
}
  