import { ListGroup } from "react-bootstrap";
import { BsGripVertical, BsSearch, BsPlusLg, BsThreeDotsVertical, BsFileText, BsCheckCircleFill } from "react-icons/bs";
import { useParams, Link } from "react-router-dom";
import assignments from "../../Database/assignments.json";


{/*Generated by AI */}
export default function Assignments() {
    const { cid } = useParams();
    
    
    const courseAssignments = assignments.filter(
        assignment => assignment.course === cid
    );

    return (
      <div id="wd-assignments">
        <div className="d-flex justify-content-between align-items-center mb-4 ms-4">
          <div className="position-relative flex-grow-1 me-3">
            <BsSearch className="position-absolute" style={{ left: "10px", top: "50%", transform: "translateY(-50%)" }} />
            <input 
              placeholder="Search..." 
              className="form-control ps-5"
              style={{ backgroundColor: '#f5f5f5' }}
            />
          </div>
          <button className="btn btn-light me-2">
            <BsPlusLg className="me-2" />Group
          </button>
          <button className="btn btn-danger">
            <BsPlusLg className="me-2" />Assignment
          </button>
        </div>

        <ListGroup className="rounded-0 ms-4" id="wd-assignments-list">
          <ListGroup.Item className="p-3 mb-4 bg-light">
            <div className="d-flex justify-content-between align-items-center">
              <div className="d-flex align-items-center">
                <BsGripVertical className="me-2 fs-5" />
                <h5 className="mb-0">ASSIGNMENTS</h5>
              </div>
              <div>
                <span className="me-2">40% of Total</span>
                <button className="btn btn-light btn-sm">
                  <BsPlusLg />
                </button>
                <button className="btn btn-light btn-sm ms-2">
                  <BsThreeDotsVertical />
                </button>
              </div>
            </div>
          </ListGroup.Item>

          {courseAssignments.map((assignment) => (
            <ListGroup.Item 
              key={assignment._id}
              className="p-3 mb-3"
              style={{ borderLeft: '4px solid #198754' }}
            >
              <Link 
                to={`/Kambaz/Courses/${cid}/Assignments/${assignment._id}`}
                className="text-decoration-none text-dark"
              >
                <div className="d-flex justify-content-between align-items-center">
                  <div>
                    <div className="d-flex align-items-center mb-2">
                      <BsGripVertical className="me-2" />
                      <BsFileText className="me-2" />
                      <h6 className="mb-0">{assignment.title}</h6>
                    </div>
                    <div className="text-muted small">
                      <span className="text-danger">Multiple Modules</span>
                      <span className="mx-2">|</span>
                      <span>100 pts</span>
                    </div>
                  </div>
                  <div>
                    <BsCheckCircleFill className="text-success me-2" />
                    <button className="btn btn-light btn-sm">
                      <BsThreeDotsVertical />
                    </button>
                  </div>
                </div>
              </Link>
            </ListGroup.Item>
          ))}
        </ListGroup>
      </div>
    );
}
  