import { createSlice } from "@reduxjs/toolkit";
import { assignments } from "../../Database";
import { v4 as uuidv4 } from "uuid";

// Generated by AI
const initialState = {
  assignments: assignments,
};

const assignmentsSlice = createSlice({
  name: "assignments",
  initialState,
  reducers: {
    addAssignment: (state, action) => {
    
      console.log('Reducer - Before adding:', state.assignments.length);
      

      const newAssignment = {
        _id: uuidv4(),
        ...action.payload,
        points: action.payload.points || 0,
        due: action.payload.due || new Date().toISOString(),
        availableFrom: action.payload.availableFrom || new Date().toISOString(),
        availableUntil: action.payload.availableUntil || new Date().toISOString(),
      };
      
      state.assignments.push(newAssignment);
      
      console.log('Reducer - After adding:', {
        newAssignment,
        totalCount: state.assignments.length,
      });
    },
    deleteAssignment: (state, { payload: assignmentId }) => {
      state.assignments = state.assignments.filter(
        (a) => a._id !== assignmentId
      );
    },
    updateAssignment: (state, { payload: assignment }) => {
      state.assignments = state.assignments.map((a) =>
        a._id === assignment._id ? assignment : a
      );
    },
    editAssignment: (state, { payload: assignmentId }) => {
      state.assignments = state.assignments.map((a) =>
        a._id === assignmentId ? { ...a, editing: true } : a
      );
    },
  },
});

export const { 
  addAssignment, 
  deleteAssignment, 
  updateAssignment, 
  editAssignment 
} = assignmentsSlice.actions;

export default assignmentsSlice.reducer;
