import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { v4 as uuidv4 } from "uuid";
import * as assignmentClient from "./client";

// Generated by AI
const initialState: any = {
  assignments: [],
};

// Create async thunk actions
export const fetchAssignments = createAsyncThunk(
  "assignments/fetchAll",
  async () => {
    return await assignmentClient.findAllAssignments();
  }
);

export const createNewAssignment = createAsyncThunk(
  "assignments/create",
  async ({ moduleId, assignment }: { moduleId: string; assignment: any }) => {
    return await assignmentClient.createAssignment(moduleId, assignment);
  }
);

export const updateExistingAssignment = createAsyncThunk(
  "assignments/update",
  async ({ assignmentId, assignment }: { assignmentId: string; assignment: any }) => {
    return await assignmentClient.updateAssignment(assignmentId, assignment);
  }
);

export const removeAssignment = createAsyncThunk(
  "assignments/delete",
  async (assignmentId: string) => {
    await assignmentClient.deleteAssignment(assignmentId);
    return assignmentId;
  }
);

const assignmentsSlice = createSlice({
  name: "assignments",
  initialState,
  reducers: {
    addAssignment: (state, action) => {

      console.log('Reducer - Before adding:', state.assignments.length);


      const newAssignment = {
        _id: uuidv4(),
        ...action.payload,
        points: action.payload.points || 0,
        due: action.payload.due || new Date().toISOString(),
        availableFrom: action.payload.availableFrom || new Date().toISOString(),
        availableUntil: action.payload.availableUntil || new Date().toISOString(),
      };

      state.assignments.push(newAssignment);

      console.log('Reducer - After adding:', {
        newAssignment,
        totalCount: state.assignments.length,
      });
    },
    deleteAssignment: (state, { payload: assignmentId }) => {
      state.assignments = state.assignments.filter(
        (a: any) => a._id !== assignmentId
      );
    },
    updateAssignment: (state, { payload: assignment }) => {
      state.assignments = state.assignments.map((a: any) =>
        a._id === assignment._id ? assignment : a
      );
    },
    editAssignment: (state, { payload: assignmentId }) => {
      state.assignments = state.assignments.map((a: any) =>
        a._id === assignmentId ? { ...a, editing: true } : a
      );
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchAssignments.fulfilled, (state, action) => {
        state.assignments = action.payload;
      })
      .addCase(createNewAssignment.fulfilled, (state, action) => {
        state.assignments.push(action.payload);
      })
      .addCase(updateExistingAssignment.fulfilled, (state, action) => {
        state.assignments = state.assignments.map((a: any) =>
          a._id === action.payload._id ? action.payload : a
        );
      })
      .addCase(removeAssignment.fulfilled, (state, action) => {
        state.assignments = state.assignments.filter(
          (a: any) => a._id !== action.payload
        );
      });
  },
});

export const {
  addAssignment,
  deleteAssignment,
  updateAssignment,
  editAssignment
} = assignmentsSlice.actions;

export default assignmentsSlice.reducer;
